Finding eigenvectors and eigenvalues.

In [11]:
import numpy as np
from numpy import linalg as LA


A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
w, v = LA.eig(A)
print(w,'\n')
print(v)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15] 

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


w - The eigenvalues, each repeated according to its multiplicity, unordered.

v - The normalized eigenvectors, such that the column v[:,i] is the eigenvector corresponding to the eigenvalue w[i].  