**Finding orthogonal and orthonormal basis using the Gram-Schmidt orthogonalization process.**

Let's note that function gs_process  takes in a matrix as an argument where rows are our initial vectors, and returns a matrix where rows are orthogonal vectors that form the new basis. 

The function normalize takes the array from gs_process and returns a new array where rows are orthonormal vectors.

In [3]:
import numpy as np
from numpy import linalg as LA


def gs_cofficient(a, b):
    denominator = np.dot(b, b)
    if denominator == 0:
        return 0
    return np.dot(a, b) / np.dot(b, b) # getting the coefficient for each b_i


def gs_process(A):
    B = []
    for i in np.arange(A.shape[0]):
        a_i = A[i]
        for b in B :
            proj_vec = gs_cofficient(a_i, b) * b
            a_i = a_i - proj_vec
        B.append(a_i)
    return np.array(B)


#example use
a1 = np.array([6, 5, 1, 0])
a2 = np.array([5, 8, 0, 1])
a3 = np.array([1, 0, 1, -1])
A = np.array([a1, a2, a3]) 
basis = gs_process(A)
print("Orthogonal basis:", basis, '\n')


# to normalize the basis:
def normalize(X):
    return np.array([x / LA.norm(x) 
                     if LA.norm(x) != 0
                     else np.zeros(len(x)) 
                     for x in X])
                     
normalized = normalize(basis)
print("Orthonormal basis:", normalized)

Orthogonal basis: [[ 6.          5.          1.          0.        ]
 [-1.77419355  2.35483871 -1.12903226  1.        ]
 [-0.30882353  0.27352941  0.48529412 -0.64411765]] 

Orthonormal basis: [[ 0.76200076  0.63500064  0.12700013  0.        ]
 [-0.53572558  0.71105395 -0.34091628  0.30195442]
 [-0.34091628  0.30195442  0.53572558 -0.71105395]]
