Finding QR decomposition.



In [1]:
import numpy as np
from numpy import linalg as LA


A = np.array([[1, 1, 0],
                [1, 0, 1],
                [0, 1, 1]])
q, r = LA.qr(A)

print("Q =", q)
print("R =", r)

is_equal = np.allclose(A, np.dot(q,r))
print("Obtained the original matrix?", is_equal)

Q= [[-0.70710678  0.40824829 -0.57735027]
 [-0.70710678 -0.40824829  0.57735027]
 [-0.          0.81649658  0.57735027]]
R= [[-1.41421356 -0.70710678 -0.70710678]
 [ 0.          1.22474487  0.40824829]
 [ 0.          0.          1.15470054]]
Obtained the original matrix? True
